#!/usr/bin/php -q
<?php

$argv[] = '--conf-file='.getcwd().'/config.php';
if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require_once __DIR__ . '/vendor/autoload.php';
} elseif (file_exists(__DIR__ . '/../../autoload.php')) {
    require_once __DIR__ . '/../../autoload.php';
}

$myo = new myo\myo;

$myo->start($argv);
